version: '2.1'

services:

  redisserver:
    image: redis
    expose:
      - "6379"
    networks:
      - mynet

  api:
    build:
      context: api
    image: api:latest
    ports:
      - "80:5000"
    environment:
      - PORT=5000
      - REDIS_LOCATION=redisserver
      - REDIS_PORT=6379
    volumes:
      - ./api/app:/app
    restart: on-failure
    depends_on:
      - redisserver
    networks:
      - mynet

networks:
  mynet:
    name: mynet-network