version: '2.1'

services:

  redisserver:
    image: redis
    expose:
      - "6379"
    networks:
      - mynet

  webapp:
    build:
      context: webapp
    image: webapp:latest
    ports:
      - "8080"
    environment:
      - REDIS_LOCATION=redisserver
      - REDIS_PORT=6379
    volumes:
      - ./webapp/app:/app
    restart: on-failure
    depends_on:
      - redisserver
    networks:
      - mynet

networks:
  mynet:
    name: mynet-network
